### ISSUE TITLE
README run with node.js instruction is wrong

### ISSUE THREAD

**Issue by stewe** [Kotlin/ts2kt#126]
Running `node build/distrib/ts2kt.js path/to/input.d.ts path/to/output.kt` results in
> ts2kt supports to convert only TypeScript definition files (d.ts)

Debugging the script showed that also path/to/input.d.ts path/to/output.kt was interpreted as a source, because it doesn't starts with '-'.

Adding '-d' works perfectly.

**Comment by Schahen** [comment]
ts2kt is deprecated, use dukat (http://github.com/Kotlin/dukat) instead.
in dukat we've never claimed to work it this way )
