### ISSUE TITLE
Let's improve ts2kt together!

### ISSUE THREAD

**Issue by GarrisonD** [Kotlin/ts2kt#45]
Hi, @bashor!

I am new to Kotlin and I like it a lot! I am also interesting in contribution to `ts2kt`.

It's difficult for me now to understand ERs (Expected Result) for existing issues.

So, may you have any small tasks for community?

Have a nice day! 🙂

**Comment by bashor** [comment]
Hi, @GarrisonD! 

Thanks for interesting, I think You can try to start from any issue marked by [e: Easy](https://github.com/Kotlin/ts2kt/labels/e%3A%20Easy).

Feel free to ask any question and don't forget to write a comment on an issue page if you going to work on it to avoid some clashes.
