### ISSUE TITLE
Classes marked as "export" on top level are not translated

### ISSUE THREAD

**Issue by hiperbou** [Kotlin/ts2kt#50]
Classes marked as "export" in this definition file are not translated to kt. It works when the class is inside a namespace, but not on top level, like in this example:
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/data/observable/observable.d.ts
Only interfaces get translated.

**Comment by koliyo** [comment]
This is really limiting!

**Comment by koliyo** [comment]
FYI, this is the one I am trying to use

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/minio/index.d.ts

**Comment by bashor** [comment]
@koliyo honestly it's incorrect d.ts file, AFAIK classes must have `declare` modifier inside d.ts file.
So you can simply workaround it by adding `declare` modifier to all class.

**Comment by bashor** [comment]
@koliyo @hiperbou since `ts2kt@0.1.3` you can use `-Xdeclare-is-optional` option to convert classes even `declare` keyword is missed.

**Comment by bashor** [comment]
According to Microsoft/TypeScript#22187 declarations are correct, so I reopen the issue
