### ISSUE TITLE
Generate typealias to Kotlin's function type when it's possible (?)

### ISSUE THREAD

**Issue by bashor** [Kotlin/ts2kt#56]
What should we do with optional parameters?
  * generate overloads
  * don't generate typealias for such cases

**Comment by epabst** [comment]
Can you provide some example typescript?

**Comment by bashor** [comment]
Something like that: 

```TypeScript
declare interface Foo {
   (string): string
}
```

```Kotlin
typealias Foo = (String) -> String
```

**Comment by Schahen** [comment]
ts2kt is deprecated, use https://github.com/Kotlin/dukat instead
In dukat we do preserve typealiases whenever it's possible.
