### ISSUE TITLE
Switch to gradle build

### ISSUE THREAD

**Issue by bashor** [Kotlin/ts2kt#76]
Pros:
* Incremental compilation
* Dogfooding (gradle integration, and IC)

Cons:
* Slow run/configuarion

**Comment by bashor** [comment]
I believe that it should be possible to work on this project in IntelliJ IDEA Community.

**Comment by bashor** [comment]
"Incremental compilation" is no longer an argument because since 1.2.70 (or even 1.2.60?) it works for IntelliJ projects too.

**Comment by epabst** [comment]
I can edit the project in IntelliJ Community but your Run Configurations require IntelliJ Ultimate.  Gradle works in Community.
