### ISSUE TITLE
Switch to generated tests

### ISSUE THREAD

**Issue by bashor** [Kotlin/ts2kt#77]
Pros:
* More convenient running part of tests
* Dogfooding for unit testing
Cons:
* Must regenerate every time after adding new tests
* Minor [1]: No navigation to testdata

[1] Minor since it will not be lost with this change, it's just unsupported for Kotlin tests

**Comment by Schahen** [comment]
Closing this once since the way testset is formed in dukat is completely different. If needed, will create a new task.
