### ISSUE TITLE
Development of the project

### ISSUE THREAD

**Issue by shevchenkobn** [Kotlin/ts2kt#82]
I have recently discovered Kotlin and liked it a lot! As for me, it fits Javascript better than Typescript.
Moreover, Kotlin provides a modern and top-notch OOP, including operator overloading. (Oh, I missed so much arbitrary types as keys in `Map` because no `hashCode()` introduced).

Kotlin provides a modern framework and excellent type safety. But the fact is that TS has already become a de-facto standard. So, existing libraries must be converted into Kotlin otherwise it will make not much sense (phew, defining every lib as dynamic).

**The question is: will the project be further developed?**
Things, that are missing are:

- adequate package name resolution using `@JsModule`, e.g. `moment.js` Kotlin files don't add it, so `moment` is not imported in transpiled code. It can be done by providing another cli argument;
- automatic resolving of all dependencies. If only output dir supplied, then use `pwd` and `app-root-path` module to define app root, checkout package.json, search for every package in `./node_modules/@types/`, convert if absent, search for `./node_modules/` (some modules include it with js code) and convert if also absent. While converting, resolve every `import` statement like described above;
- fix minor issues, listed in issues and some other (e.g. it appends override to `valueOf` method, but there is not in `Any` type).

_P.S. I initially forked it to do develop it, but I realised that it is to tough to do along considering my poor knowledge of both Kotlin and tsc API._
**If someone supports the idea or already developing in a fork I am eager to take part**

**Comment by bashor** [comment]
> The question is: will the project be further developed?

Sure! We will continue working on it! 

> Things, that are missing are:

Please report them as separate issues.

> If someone supports the idea or already developing in a fork I am eager to take part

You can contribute to this! :)

We will be glad to any kind of contribution!
It can be:
* Docs (tutorials, posts, etc.)
* New declarations in [Kotlin/js-externals](https://github.com/Kotlin/js-externals)
* Contribute to this project (ts2kt)

And we ready to help you and any other contributor with it.
